### ISSUE TITLE
netatalk compatibility

### ISSUE THREAD

**Issue by voron** [juhovh/shairplay#34]
I had used shairplay for year or so. Now I installed netatalk to implement time machine. The problem is that both sharplay and netatalk depends on avahi, but netatalk cannot be installed with mdnsresponder-compat, used by shairplay. I can add shairplay service to avahi manually, but shairplay cannot start without mdnsresponder-compat with error
`ERROR: Could not initialize dnssd library!`
Both these apps are useful for me, and, if shairplay cannot be updated to not use mdnsresponder-compat, then it will be great to just start without dnssd, notifying about manual avahi configuration requirement.

**Comment by juhovh** [comment]
I believe netatalk can be compiled to use dns_sd only, which might fix your problem. But that's kind of an ugly solution.

Proper Avahi support (without mdnsresponder-compat) has been on the backlog for a long time now, but there hasn't really been an incentive for it, so it's not on high priority. However I guess I'll need to start looking into this, since your use case seems to be valid.

**Comment by voron** [comment]
>I believe netatalk can be compiled to use dns_sd only, which might fix your problem
Yes, it seems to be that, according to http://sourceforge.net/p/netatalk/bugs/586/ - I use gentoo :) There are some mdnsresponder-compat & netatalk related gentoo bugs - another software needs compat, so I will close this bug
