### ISSUE TITLE
autogen.sh failed. possibly undefined macro: AC_PROG_LIBTOOL

### ISSUE THREAD

**Issue by britus** [juhovh/shairplay#77]
root@udoo:~/src/shairplay# ./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:13: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:14: error: possibly undefined macro: AC_PROG_LIBTOOL
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by juhovh** [comment]
You don't have your operating system mentioned, but it looks like you need to have libtool installed for the autoconf to work correctly, because it tries to compile libshairplay as a shared library using libtool. Please install libtool and try again, if that is not possible for some reason or doesn't help, please reopen this issue.
